create table if not exists public.activities (
  id uuid primary key default gen_random_uuid(),
  title varchar(80) not null,
  body text not null,
  cover_url text,
  action_label varchar(30),
  action_url text,
  publish_at timestamptz not null,
  starts_at timestamptz not null,
  ends_at timestamptz not null,
  reward_amount bigint not null default 0,
  is_active boolean not null default true,
  created_by uuid not null references auth.users(id) on delete restrict,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint activities_title_check check (
    title = btrim(title) and char_length(title) > 0
  ),
  constraint activities_body_check check (
    body = btrim(body) and char_length(body) > 0
  ),
  constraint activities_cover_url_check check (
    cover_url is null
    or (cover_url = btrim(cover_url) and char_length(cover_url) > 0)
  ),
  constraint activities_action_check check (
    (action_label is null and action_url is null)
    or (
      action_label is not null
      and action_label = btrim(action_label)
      and char_length(action_label) > 0
      and action_url is not null
      and action_url = btrim(action_url)
      and char_length(action_url) > 0
    )
  ),
  constraint activities_schedule_check check (
    publish_at <= starts_at and starts_at < ends_at
  ),
  constraint activities_reward_amount_check check (
    reward_amount between 0 and 1000000
  )
);

create table if not exists public.activity_claims (
  activity_id uuid not null
    references public.activities(id) on delete restrict,
  user_id uuid not null
    references public.profiles(id) on delete cascade,
  reward_amount bigint not null,
  claimed_at timestamptz not null default now(),
  primary key (activity_id, user_id),
  constraint activity_claims_reward_amount_check check (
    reward_amount between 0 and 1000000
  )
);

create table if not exists public.site_notifications (
  id uuid primary key default gen_random_uuid(),
  activity_id uuid references public.activities(id) on delete restrict,
  title varchar(80) not null,
  body text not null,
  reward_amount bigint not null default 0,
  visible_at timestamptz not null,
  expires_at timestamptz,
  is_active boolean not null default true,
  created_by uuid not null references auth.users(id) on delete restrict,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint site_notifications_title_check check (
    title = btrim(title) and char_length(title) > 0
  ),
  constraint site_notifications_body_check check (
    body = btrim(body) and char_length(body) > 0
  ),
  constraint site_notifications_reward_amount_check check (
    reward_amount between 0 and 1000000
  ),
  constraint site_notifications_expiry_check check (
    expires_at is null or expires_at > visible_at
  ),
  constraint site_notifications_activity_reward_check check (
    activity_id is null or reward_amount = 0
  )
);

create table if not exists public.notification_reads (
  notification_id uuid not null
    references public.site_notifications(id) on delete cascade,
  user_id uuid not null
    references public.profiles(id) on delete cascade,
  read_at timestamptz not null default now(),
  primary key (notification_id, user_id)
);

create table if not exists public.notification_claims (
  notification_id uuid not null
    references public.site_notifications(id) on delete restrict,
  user_id uuid not null
    references public.profiles(id) on delete cascade,
  reward_amount bigint not null,
  claimed_at timestamptz not null default now(),
  primary key (notification_id, user_id),
  constraint notification_claims_reward_amount_check check (
    reward_amount between 0 and 1000000
  )
);

create table if not exists public.checkin_rule_versions (
  id bigint generated by default as identity primary key,
  effective_from date not null unique,
  monday_reward bigint not null,
  tuesday_reward bigint not null,
  wednesday_reward bigint not null,
  thursday_reward bigint not null,
  friday_reward bigint not null,
  saturday_reward bigint not null,
  sunday_reward bigint not null,
  makeup_cost bigint not null,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  constraint checkin_rule_versions_monday_reward_check check (
    monday_reward between 0 and 1000000
  ),
  constraint checkin_rule_versions_tuesday_reward_check check (
    tuesday_reward between 0 and 1000000
  ),
  constraint checkin_rule_versions_wednesday_reward_check check (
    wednesday_reward between 0 and 1000000
  ),
  constraint checkin_rule_versions_thursday_reward_check check (
    thursday_reward between 0 and 1000000
  ),
  constraint checkin_rule_versions_friday_reward_check check (
    friday_reward between 0 and 1000000
  ),
  constraint checkin_rule_versions_saturday_reward_check check (
    saturday_reward between 0 and 1000000
  ),
  constraint checkin_rule_versions_sunday_reward_check check (
    sunday_reward between 0 and 1000000
  ),
  constraint checkin_rule_versions_makeup_cost_check check (
    makeup_cost between 0 and 1000000
  )
);

create table if not exists public.player_checkins (
  user_id uuid not null
    references public.profiles(id) on delete cascade,
  checkin_date date not null,
  checkin_type text not null,
  reward_amount bigint not null,
  payment_method text not null,
  payment_amount bigint not null default 0,
  created_at timestamptz not null default now(),
  primary key (user_id, checkin_date),
  constraint player_checkins_type_check check (
    checkin_type in ('daily', 'makeup')
  ),
  constraint player_checkins_reward_amount_check check (
    reward_amount between 0 and 1000000
  ),
  constraint player_checkins_payment_method_check check (
    payment_method in ('none', 'coins', 'item')
  ),
  constraint player_checkins_payment_amount_check check (
    payment_amount between 0 and 1000000
  ),
  constraint player_checkins_payment_consistency_check check (
    (
      checkin_type = 'daily'
      and payment_method = 'none'
      and payment_amount = 0
    )
    or (
      checkin_type = 'makeup'
      and payment_method = 'coins'
    )
    or (
      checkin_type = 'makeup'
      and payment_method = 'item'
      and payment_amount = 1
    )
  )
);

create index if not exists activities_visible_window_idx
on public.activities (is_active, publish_at desc, ends_at, starts_at);

create unique index if not exists site_notifications_activity_unique_idx
on public.site_notifications (activity_id)
where activity_id is not null;

create index if not exists site_notifications_visible_cursor_idx
on public.site_notifications (is_active, visible_at desc, id desc);

create index if not exists notification_reads_user_idx
on public.notification_reads (user_id, read_at desc, notification_id);

create index if not exists checkin_rule_versions_effective_idx
on public.checkin_rule_versions (effective_from desc);

create index if not exists player_checkins_user_month_idx
on public.player_checkins (user_id, checkin_date desc);

insert into public.checkin_rule_versions (
  effective_from,
  monday_reward,
  tuesday_reward,
  wednesday_reward,
  thursday_reward,
  friday_reward,
  saturday_reward,
  sunday_reward,
  makeup_cost
) values (
  date '1970-01-01',
  10,
  10,
  10,
  10,
  10,
  10,
  10,
  20
)
on conflict (effective_from) do nothing;

create or replace function public.site_local_date()
returns date
language sql
stable
set search_path = public, pg_temp
as $$
  select (now() at time zone 'Asia/Hong_Kong')::date;
$$;

create or replace function public.require_registered_user()
returns uuid
language plpgsql
stable
security definer
set search_path = public, pg_temp
as $$
declare
  v_user_id uuid := auth.uid();
begin
  if v_user_id is null
     or not exists (
       select 1 from public.profiles where id = v_user_id
     )
     or not exists (
       select 1 from public.player_wallets where user_id = v_user_id
     ) then
    raise exception 'REGISTERED_ACCOUNT_REQUIRED';
  end if;

  return v_user_id;
end;
$$;

create or replace function public.require_site_admin()
returns uuid
language plpgsql
stable
security definer
set search_path = public, pg_temp
as $$
declare
  v_user_id uuid := auth.uid();
begin
  if v_user_id is null or not public.is_economy_admin(v_user_id) then
    raise exception 'ADMIN_REQUIRED';
  end if;

  return v_user_id;
end;
$$;

create or replace function public.checkin_rule_for_date(p_date date)
returns public.checkin_rule_versions
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select rule
  from public.checkin_rule_versions as rule
  where rule.effective_from <= p_date
  order by rule.effective_from desc
  limit 1;
$$;

create or replace function public.validate_public_url(
  p_value text,
  p_allow_relative boolean default false
)
returns text
language plpgsql
immutable
set search_path = public, pg_temp
as $$
declare
  v_value text := btrim(p_value);
  v_authority text;
begin
  if p_value is null or v_value = '' then
    return null;
  end if;

  if v_value ~ '[[:cntrl:]]'
     or v_value ~ '[[:space:]]'
     or strpos(v_value, chr(92)) > 0 then
    raise exception 'INVALID_PUBLIC_URL';
  end if;

  if lower(left(v_value, 8)) = 'https://' then
    v_authority := split_part(
      split_part(
        split_part(substring(v_value from 9), '/', 1),
        '?',
        1
      ),
      '#',
      1
    );

    if v_authority = '' then
      raise exception 'INVALID_PUBLIC_URL';
    end if;

    return v_value;
  end if;

  if coalesce(p_allow_relative, false)
     and left(v_value, 1) = '/'
     and left(v_value, 2) <> '//' then
    return v_value;
  end if;

  raise exception 'INVALID_PUBLIC_URL';
end;
$$;

create or replace function public.list_active_activities()
returns table (
  id uuid,
  title text,
  body text,
  cover_url text,
  action_label text,
  action_url text,
  publish_at timestamptz,
  starts_at timestamptz,
  ends_at timestamptz,
  reward_amount bigint,
  claimed boolean,
  claimed_at timestamptz
)
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select
    activity.id,
    activity.title::text,
    activity.body,
    activity.cover_url,
    activity.action_label::text,
    activity.action_url,
    activity.publish_at,
    activity.starts_at,
    activity.ends_at,
    activity.reward_amount,
    claim.claimed_at is not null as claimed,
    claim.claimed_at
  from public.activities as activity
  left join public.activity_claims as claim
    on claim.activity_id = activity.id
   and claim.user_id = auth.uid()
   and exists (
     select 1
     from public.profiles as profile
     join public.player_wallets as wallet on wallet.user_id = profile.id
     where profile.id = auth.uid()
   )
  where activity.is_active
    and activity.publish_at <= now()
    and activity.ends_at > now()
  order by activity.publish_at desc, activity.id desc;
$$;

create or replace function public.claim_activity_reward(
  p_activity_id uuid,
  p_request_id uuid
)
returns table (
  reward_amount bigint,
  balance bigint,
  claimed_at timestamptz
)
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_user_id uuid := public.require_registered_user();
  v_activity public.activities%rowtype;
  v_balance bigint;
  v_claimed_at timestamptz;
begin
  if p_request_id is null then
    raise exception 'REQUEST_ID_REQUIRED';
  end if;

  select wallet.balance
  into v_balance
  from public.player_wallets as wallet
  where wallet.user_id = v_user_id
  for update;

  select activity.*
  into v_activity
  from public.activities as activity
  where activity.id = p_activity_id
  for update;

  if not found then
    raise exception 'ACTIVITY_NOT_FOUND';
  end if;
  if not v_activity.is_active then
    raise exception 'ACTIVITY_DISABLED';
  end if;
  if v_activity.publish_at > now() then
    raise exception 'ACTIVITY_NOT_PUBLISHED';
  end if;
  if v_activity.starts_at > now() then
    raise exception 'ACTIVITY_NOT_STARTED';
  end if;
  if v_activity.ends_at <= now() then
    raise exception 'ACTIVITY_ENDED';
  end if;

  begin
    insert into public.activity_claims (
      activity_id,
      user_id,
      reward_amount
    ) values (
      v_activity.id,
      v_user_id,
      v_activity.reward_amount
    )
    returning activity_claims.claimed_at into v_claimed_at;
  exception
    when unique_violation then
      raise exception 'ACTIVITY_ALREADY_CLAIMED';
  end;

  if v_activity.reward_amount <> 0 then
    v_balance := public.apply_coin_delta(
      v_user_id,
      v_activity.reward_amount,
      'activity_reward',
      v_activity.id::text,
      'activity_reward:' || v_activity.id::text || ':' || v_user_id::text
    );
  end if;

  return query
  select v_activity.reward_amount, v_balance, v_claimed_at;
end;
$$;

create or replace function public.admin_list_activities()
returns table (
  id uuid,
  title text,
  body text,
  cover_url text,
  action_label text,
  action_url text,
  publish_at timestamptz,
  starts_at timestamptz,
  ends_at timestamptz,
  reward_amount bigint,
  is_active boolean,
  created_by uuid,
  created_at timestamptz,
  updated_at timestamptz,
  claim_count bigint
)
language plpgsql
stable
security definer
set search_path = public, pg_temp
as $$
begin
  perform public.require_site_admin();

  return query
  select
    activity.id,
    activity.title::text,
    activity.body,
    activity.cover_url,
    activity.action_label::text,
    activity.action_url,
    activity.publish_at,
    activity.starts_at,
    activity.ends_at,
    activity.reward_amount,
    activity.is_active,
    activity.created_by,
    activity.created_at,
    activity.updated_at,
    (
      select count(*)
      from public.activity_claims as claim
      where claim.activity_id = activity.id
    ) as claim_count
  from public.activities as activity
  order by activity.created_at desc, activity.id desc;
end;
$$;

create or replace function public.admin_save_activity(
  p_id uuid,
  p_title text,
  p_body text,
  p_cover_url text,
  p_action_label text,
  p_action_url text,
  p_publish_at timestamptz,
  p_starts_at timestamptz,
  p_ends_at timestamptz,
  p_reward_amount bigint
)
returns public.activities
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_admin_id uuid := public.require_site_admin();
  v_title text := btrim(p_title);
  v_body text := btrim(p_body);
  v_cover_url text := public.validate_public_url(p_cover_url, false);
  v_action_label text := nullif(btrim(p_action_label), '');
  v_action_url text := public.validate_public_url(p_action_url, true);
  v_activity public.activities%rowtype;
begin
  if v_title is null or v_title = '' or char_length(v_title) > 80 then
    raise exception 'INVALID_ACTIVITY_TITLE';
  end if;
  if v_body is null or v_body = '' then
    raise exception 'INVALID_ACTIVITY_BODY';
  end if;
  if (v_action_label is null) <> (v_action_url is null)
     or char_length(v_action_label) > 30 then
    raise exception 'INVALID_ACTIVITY_ACTION';
  end if;
  if p_publish_at is null
     or p_starts_at is null
     or p_ends_at is null
     or p_publish_at > p_starts_at
     or p_starts_at >= p_ends_at then
    raise exception 'INVALID_ACTIVITY_WINDOW';
  end if;
  if p_reward_amount is null or p_reward_amount not between 0 and 1000000 then
    raise exception 'INVALID_ACTIVITY_REWARD';
  end if;

  if p_id is null then
    insert into public.activities (
      title,
      body,
      cover_url,
      action_label,
      action_url,
      publish_at,
      starts_at,
      ends_at,
      reward_amount,
      created_by
    ) values (
      v_title,
      v_body,
      v_cover_url,
      v_action_label,
      v_action_url,
      p_publish_at,
      p_starts_at,
      p_ends_at,
      p_reward_amount,
      v_admin_id
    )
    returning * into v_activity;
  else
    select activity.*
    into v_activity
    from public.activities as activity
    where activity.id = p_id
    for update;

    if not found then
      raise exception 'ACTIVITY_NOT_FOUND';
    end if;

    update public.activities as activity
    set title = v_title,
        body = v_body,
        cover_url = v_cover_url,
        action_label = v_action_label,
        action_url = v_action_url,
        publish_at = p_publish_at,
        starts_at = p_starts_at,
        ends_at = p_ends_at,
        reward_amount = p_reward_amount,
        is_active = true,
        updated_at = now()
    where activity.id = p_id
    returning activity.* into v_activity;
  end if;

  insert into public.site_notifications (
    activity_id,
    title,
    body,
    reward_amount,
    visible_at,
    expires_at,
    is_active,
    created_by
  ) values (
    v_activity.id,
    v_activity.title,
    v_activity.body,
    0,
    v_activity.publish_at,
    v_activity.ends_at,
    true,
    v_admin_id
  )
  on conflict (activity_id) where activity_id is not null
  do update set
    title = excluded.title,
    body = excluded.body,
    reward_amount = 0,
    visible_at = excluded.visible_at,
    expires_at = excluded.expires_at,
    is_active = true,
    updated_at = now();

  return v_activity;
end;
$$;

create or replace function public.admin_unpublish_activity(p_activity_id uuid)
returns public.activities
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_activity public.activities%rowtype;
begin
  perform public.require_site_admin();

  select activity.*
  into v_activity
  from public.activities as activity
  where activity.id = p_activity_id
  for update;

  if not found then
    raise exception 'ACTIVITY_NOT_FOUND';
  end if;

  update public.activities as activity
  set is_active = false,
      updated_at = now()
  where activity.id = p_activity_id
  returning activity.* into v_activity;

  update public.site_notifications as notification
  set is_active = false,
      updated_at = now()
  where notification.activity_id = p_activity_id;

  return v_activity;
end;
$$;

create or replace function public.list_site_notifications(
  p_before_visible_at timestamptz default null,
  p_before_id uuid default null,
  p_limit integer default 20
)
returns table (
  id uuid,
  activity_id uuid,
  title text,
  body text,
  reward_amount bigint,
  visible_at timestamptz,
  expires_at timestamptz,
  action_url text,
  is_read boolean,
  reward_claimed boolean,
  read_at timestamptz,
  reward_claimed_at timestamptz
)
language plpgsql
stable
security definer
set search_path = public, pg_temp
as $$
declare
  v_user_id uuid := auth.uid();
  v_registered boolean;
begin
  if (p_before_visible_at is null) <> (p_before_id is null) then
    raise exception 'INVALID_NOTIFICATION_CURSOR';
  end if;
  if p_limit is null or p_limit < 1 or p_limit > 50 then
    raise exception 'INVALID_NOTIFICATION_LIMIT';
  end if;

  v_registered := v_user_id is not null
    and exists (select 1 from public.profiles where profiles.id = v_user_id)
    and exists (select 1 from public.player_wallets where player_wallets.user_id = v_user_id);

  return query
  select
    notification.id,
    notification.activity_id,
    notification.title::text,
    notification.body,
    notification.reward_amount,
    notification.visible_at,
    notification.expires_at,
    case
      when notification.activity_id is not null then
        '/player/?tab=activities&activity=' || notification.activity_id::text
      else null
    end as action_url,
    case when v_registered then read.read_at is not null else false end as is_read,
    case when v_registered then claim.claimed_at is not null else false end as reward_claimed,
    case when v_registered then read.read_at else null end as read_at,
    case when v_registered then claim.claimed_at else null end as reward_claimed_at
  from public.site_notifications as notification
  left join public.notification_reads as read
    on read.notification_id = notification.id
   and read.user_id = v_user_id
  left join public.notification_claims as claim
    on claim.notification_id = notification.id
   and claim.user_id = v_user_id
  where notification.is_active
    and notification.visible_at <= now()
    and (notification.expires_at is null or notification.expires_at > now())
    and (
      p_before_visible_at is null
      or (notification.visible_at, notification.id) < (p_before_visible_at, p_before_id)
    )
  order by notification.visible_at desc, notification.id desc
  limit p_limit;
end;
$$;

create or replace function public.count_unread_site_notifications()
returns bigint
language plpgsql
stable
security definer
set search_path = public, pg_temp
as $$
declare
  v_user_id uuid := public.require_registered_user();
  v_count bigint;
begin
  select count(*)
  into v_count
  from public.site_notifications as notification
  where notification.is_active
    and notification.visible_at <= now()
    and (notification.expires_at is null or notification.expires_at > now())
    and not exists (
      select 1
      from public.notification_reads as read
      where read.notification_id = notification.id
        and read.user_id = v_user_id
    );

  return v_count;
end;
$$;

create or replace function public.mark_site_notification_read(p_notification_id uuid)
returns table (
  notification_id uuid,
  read_at timestamptz
)
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_user_id uuid := public.require_registered_user();
  v_notification public.site_notifications%rowtype;
begin
  select notification.*
  into v_notification
  from public.site_notifications as notification
  where notification.id = p_notification_id
  for update;

  if not found then
    raise exception 'NOTIFICATION_NOT_FOUND';
  end if;
  if not v_notification.is_active then
    raise exception 'NOTIFICATION_DISABLED';
  end if;
  if v_notification.visible_at > now() then
    raise exception 'NOTIFICATION_NOT_VISIBLE';
  end if;
  if v_notification.expires_at is not null and v_notification.expires_at <= now() then
    raise exception 'NOTIFICATION_EXPIRED';
  end if;

  insert into public.notification_reads (notification_id, user_id)
  values (v_notification.id, v_user_id)
  on conflict on constraint notification_reads_pkey do nothing;

  return query
  select read.notification_id, read.read_at
  from public.notification_reads as read
  where read.notification_id = v_notification.id
    and read.user_id = v_user_id;
end;
$$;

create or replace function public.claim_site_notification_reward(
  p_notification_id uuid,
  p_request_id uuid
)
returns table (
  reward_amount bigint,
  balance bigint,
  claimed_at timestamptz
)
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_user_id uuid := public.require_registered_user();
  v_notification public.site_notifications%rowtype;
  v_balance bigint;
  v_claimed_at timestamptz;
begin
  if p_request_id is null then
    raise exception 'REQUEST_ID_REQUIRED';
  end if;

  select wallet.balance
  into v_balance
  from public.player_wallets as wallet
  where wallet.user_id = v_user_id
  for update;

  select notification.*
  into v_notification
  from public.site_notifications as notification
  where notification.id = p_notification_id
  for update;

  if not found then
    raise exception 'NOTIFICATION_NOT_FOUND';
  end if;
  if not v_notification.is_active then
    raise exception 'NOTIFICATION_DISABLED';
  end if;
  if v_notification.visible_at > now() then
    raise exception 'NOTIFICATION_NOT_VISIBLE';
  end if;
  if v_notification.expires_at is not null and v_notification.expires_at <= now() then
    raise exception 'NOTIFICATION_EXPIRED';
  end if;
  if v_notification.reward_amount <= 0 then
    raise exception 'NOTIFICATION_NO_REWARD';
  end if;

  begin
    insert into public.notification_claims (
      notification_id,
      user_id,
      reward_amount
    ) values (
      v_notification.id,
      v_user_id,
      v_notification.reward_amount
    )
    returning notification_claims.claimed_at into v_claimed_at;
  exception
    when unique_violation then
      raise exception 'NOTIFICATION_ALREADY_CLAIMED';
  end;

  v_balance := public.apply_coin_delta(
    v_user_id,
    v_notification.reward_amount,
    'notification_reward',
    v_notification.id::text,
    'notification_reward:' || v_notification.id::text || ':' || v_user_id::text
  );

  return query
  select v_notification.reward_amount, v_balance, v_claimed_at;
end;
$$;

create or replace function public.admin_list_site_notifications()
returns table (
  id uuid,
  activity_id uuid,
  title text,
  body text,
  reward_amount bigint,
  visible_at timestamptz,
  expires_at timestamptz,
  is_active boolean,
  created_by uuid,
  created_at timestamptz,
  updated_at timestamptz,
  read_count bigint,
  claim_count bigint
)
language plpgsql
stable
security definer
set search_path = public, pg_temp
as $$
begin
  perform public.require_site_admin();

  return query
  select
    notification.id,
    notification.activity_id,
    notification.title::text,
    notification.body,
    notification.reward_amount,
    notification.visible_at,
    notification.expires_at,
    notification.is_active,
    notification.created_by,
    notification.created_at,
    notification.updated_at,
    (
      select count(*)
      from public.notification_reads as read
      where read.notification_id = notification.id
    ) as read_count,
    (
      select count(*)
      from public.notification_claims as claim
      where claim.notification_id = notification.id
    ) as claim_count
  from public.site_notifications as notification
  order by notification.created_at desc, notification.id desc;
end;
$$;

create or replace function public.admin_publish_site_notification(
  p_title text,
  p_body text,
  p_reward_amount bigint,
  p_visible_at timestamptz,
  p_expires_at timestamptz default null
)
returns public.site_notifications
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_admin_id uuid := public.require_site_admin();
  v_title text := btrim(p_title);
  v_body text := btrim(p_body);
  v_notification public.site_notifications%rowtype;
begin
  if v_title is null or v_title = '' or char_length(v_title) > 80 then
    raise exception 'INVALID_NOTIFICATION_TITLE';
  end if;
  if v_body is null or v_body = '' then
    raise exception 'INVALID_NOTIFICATION_BODY';
  end if;
  if p_reward_amount is null or p_reward_amount not between 0 and 1000000 then
    raise exception 'INVALID_NOTIFICATION_REWARD';
  end if;
  if p_visible_at is null
     or (p_expires_at is not null and p_expires_at <= p_visible_at) then
    raise exception 'INVALID_NOTIFICATION_WINDOW';
  end if;

  insert into public.site_notifications (
    activity_id,
    title,
    body,
    reward_amount,
    visible_at,
    expires_at,
    is_active,
    created_by
  ) values (
    null,
    v_title,
    v_body,
    p_reward_amount,
    p_visible_at,
    p_expires_at,
    true,
    v_admin_id
  )
  returning * into v_notification;

  return v_notification;
end;
$$;

create or replace function public.admin_disable_site_notification(p_notification_id uuid)
returns public.site_notifications
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_notification public.site_notifications%rowtype;
begin
  perform public.require_site_admin();

  select notification.*
  into v_notification
  from public.site_notifications as notification
  where notification.id = p_notification_id
  for update;

  if not found then
    raise exception 'NOTIFICATION_NOT_FOUND';
  end if;

  update public.site_notifications as notification
  set is_active = false,
      updated_at = now()
  where notification.id = p_notification_id
  returning notification.* into v_notification;

  return v_notification;
end;
$$;

create or replace function public.get_checkin_month(p_month date)
returns table (
  checkin_date date,
  reward_amount bigint,
  checked_in boolean,
  checkin_type text,
  payment_method text,
  payment_amount bigint,
  is_today boolean,
  can_makeup boolean,
  makeup_cost bigint
)
language plpgsql
stable
security definer
set search_path = public, pg_temp
as $$
declare
  v_user_id uuid := public.require_registered_user();
  v_today date := public.site_local_date();
  v_month_start date;
  v_current_month date;
begin
  if p_month is null then
    raise exception 'INVALID_CHECKIN_MONTH';
  end if;

  v_month_start := date_trunc('month', p_month)::date;
  v_current_month := date_trunc('month', v_today)::date;

  if v_month_start > v_current_month then
    raise exception 'INVALID_CHECKIN_MONTH';
  end if;

  return query
  select
    calendar.checkin_date,
    coalesce(
      checkin.reward_amount,
      case extract(isodow from calendar.checkin_date)::integer
        when 1 then rule.monday_reward
        when 2 then rule.tuesday_reward
        when 3 then rule.wednesday_reward
        when 4 then rule.thursday_reward
        when 5 then rule.friday_reward
        when 6 then rule.saturday_reward
        when 7 then rule.sunday_reward
      end
    ) as reward_amount,
    checkin.user_id is not null as checked_in,
    checkin.checkin_type,
    checkin.payment_method,
    checkin.payment_amount,
    calendar.checkin_date = v_today as is_today,
    v_month_start = v_current_month
      and calendar.checkin_date < v_today
      and checkin.user_id is null as can_makeup,
    rule.makeup_cost
  from generate_series(
    v_month_start,
    (v_month_start + interval '1 month - 1 day')::date,
    interval '1 day'
  ) as days(day_value)
  cross join lateral (
    select days.day_value::date as checkin_date
  ) as calendar
  cross join lateral public.checkin_rule_for_date(calendar.checkin_date) as rule
  left join public.player_checkins as checkin
    on checkin.user_id = v_user_id
   and checkin.checkin_date = calendar.checkin_date
  order by calendar.checkin_date;
end;
$$;

create or replace function public.perform_daily_checkin(p_request_id uuid)
returns table (
  checkin_date date,
  reward_amount bigint,
  balance bigint,
  checkin_type text,
  payment_method text,
  payment_amount bigint
)
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_user_id uuid := public.require_registered_user();
  v_date date := public.site_local_date();
  v_rule public.checkin_rule_versions%rowtype;
  v_checkin public.player_checkins%rowtype;
  v_reward bigint;
  v_balance bigint;
begin
  if p_request_id is null then
    raise exception 'INVALID_REQUEST_ID';
  end if;

  select wallet.balance
  into v_balance
  from public.player_wallets as wallet
  where wallet.user_id = v_user_id
  for update;

  select rule.*
  into v_rule
  from public.checkin_rule_for_date(v_date) as rule;

  if not found then
    raise exception 'INVALID_CHECKIN_RULE';
  end if;

  if exists (
    select 1
    from public.player_checkins as checkin
    where checkin.user_id = v_user_id
      and checkin.checkin_date = v_date
  ) then
    raise exception 'CHECKIN_ALREADY_DONE';
  end if;

  v_reward := case extract(isodow from v_date)::integer
    when 1 then v_rule.monday_reward
    when 2 then v_rule.tuesday_reward
    when 3 then v_rule.wednesday_reward
    when 4 then v_rule.thursday_reward
    when 5 then v_rule.friday_reward
    when 6 then v_rule.saturday_reward
    when 7 then v_rule.sunday_reward
  end;

  begin
    insert into public.player_checkins as checkin (
      user_id,
      checkin_date,
      checkin_type,
      reward_amount,
      payment_method,
      payment_amount
    ) values (
      v_user_id,
      v_date,
      'daily',
      v_reward,
      'none',
      0
    )
    returning checkin.* into v_checkin;
  exception
    when unique_violation then
      raise exception 'CHECKIN_ALREADY_DONE';
  end;

  if v_reward <> 0 then
    v_balance := public.apply_coin_delta(
      v_user_id,
      v_reward,
      'checkin_daily',
      v_date::text,
      'checkin:daily:' || v_user_id::text || ':' || v_date::text
    );
  end if;

  return query
  select
    v_checkin.checkin_date,
    v_checkin.reward_amount,
    v_balance,
    v_checkin.checkin_type,
    v_checkin.payment_method,
    v_checkin.payment_amount;
end;
$$;

create or replace function public.perform_makeup_checkin(
  p_date date,
  p_payment_method text,
  p_request_id uuid
)
returns table (
  checkin_date date,
  reward_amount bigint,
  balance bigint,
  checkin_type text,
  payment_method text,
  payment_amount bigint
)
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_user_id uuid := public.require_registered_user();
  v_today date := public.site_local_date();
  v_current_month date := date_trunc('month', v_today)::date;
  v_rule public.checkin_rule_versions%rowtype;
  v_checkin public.player_checkins%rowtype;
  v_reward bigint;
  v_balance bigint;
begin
  if p_request_id is null then
    raise exception 'INVALID_REQUEST_ID';
  end if;

  select wallet.balance
  into v_balance
  from public.player_wallets as wallet
  where wallet.user_id = v_user_id
  for update;

  if p_date is null or p_date >= v_today then
    raise exception 'MAKEUP_DATE_INVALID';
  end if;

  if date_trunc('month', p_date)::date <> v_current_month then
    raise exception 'MAKEUP_OUTSIDE_CURRENT_MONTH';
  end if;

  if exists (
    select 1
    from public.player_checkins as checkin
    where checkin.user_id = v_user_id
      and checkin.checkin_date = p_date
  ) then
    raise exception 'CHECKIN_ALREADY_DONE';
  end if;

  if p_payment_method = 'item' then
    raise exception 'ITEM_PAYMENT_UNAVAILABLE';
  end if;
  if p_payment_method is distinct from 'coins' then
    raise exception 'INVALID_PAYMENT_METHOD';
  end if;

  select rule.*
  into v_rule
  from public.checkin_rule_for_date(p_date) as rule;

  if not found then
    raise exception 'INVALID_CHECKIN_RULE';
  end if;

  v_reward := case extract(isodow from p_date)::integer
    when 1 then v_rule.monday_reward
    when 2 then v_rule.tuesday_reward
    when 3 then v_rule.wednesday_reward
    when 4 then v_rule.thursday_reward
    when 5 then v_rule.friday_reward
    when 6 then v_rule.saturday_reward
    when 7 then v_rule.sunday_reward
  end;

  begin
    insert into public.player_checkins as checkin (
      user_id,
      checkin_date,
      checkin_type,
      reward_amount,
      payment_method,
      payment_amount
    ) values (
      v_user_id,
      p_date,
      'makeup',
      v_reward,
      'coins',
      v_rule.makeup_cost
    )
    returning checkin.* into v_checkin;
  exception
    when unique_violation then
      raise exception 'CHECKIN_ALREADY_DONE';
  end;

  if v_rule.makeup_cost <> 0 then
    v_balance := public.apply_coin_delta(
      v_user_id,
      -v_rule.makeup_cost,
      'checkin_makeup_cost',
      p_date::text,
      'checkin:makeup:cost:' || v_user_id::text || ':' || p_date::text
    );
  end if;

  if v_reward <> 0 then
    v_balance := public.apply_coin_delta(
      v_user_id,
      v_reward,
      'checkin_makeup_reward',
      p_date::text,
      'checkin:makeup:reward:' || v_user_id::text || ':' || p_date::text
    );
  end if;

  return query
  select
    v_checkin.checkin_date,
    v_checkin.reward_amount,
    v_balance,
    v_checkin.checkin_type,
    v_checkin.payment_method,
    v_checkin.payment_amount;
end;
$$;

create or replace function public.admin_list_checkin_rules()
returns table (
  id bigint,
  effective_from date,
  monday_reward bigint,
  tuesday_reward bigint,
  wednesday_reward bigint,
  thursday_reward bigint,
  friday_reward bigint,
  saturday_reward bigint,
  sunday_reward bigint,
  makeup_cost bigint,
  created_by uuid,
  created_at timestamptz
)
language plpgsql
stable
security definer
set search_path = public, pg_temp
as $$
begin
  perform public.require_site_admin();

  return query
  select
    rule.id,
    rule.effective_from,
    rule.monday_reward,
    rule.tuesday_reward,
    rule.wednesday_reward,
    rule.thursday_reward,
    rule.friday_reward,
    rule.saturday_reward,
    rule.sunday_reward,
    rule.makeup_cost,
    rule.created_by,
    rule.created_at
  from public.checkin_rule_versions as rule
  order by rule.effective_from desc, rule.id desc;
end;
$$;

create or replace function public.admin_create_checkin_rule(
  p_effective_from date,
  p_monday_reward bigint,
  p_tuesday_reward bigint,
  p_wednesday_reward bigint,
  p_thursday_reward bigint,
  p_friday_reward bigint,
  p_saturday_reward bigint,
  p_sunday_reward bigint,
  p_makeup_cost bigint
)
returns public.checkin_rule_versions
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_admin_id uuid := public.require_site_admin();
  v_today date := public.site_local_date();
  v_rule public.checkin_rule_versions%rowtype;
begin
  if p_effective_from is null or p_effective_from < v_today then
    raise exception 'CHECKIN_RULE_DATE_INVALID';
  end if;

  if exists (
    select 1
    from unnest(array[
      p_monday_reward,
      p_tuesday_reward,
      p_wednesday_reward,
      p_thursday_reward,
      p_friday_reward,
      p_saturday_reward,
      p_sunday_reward,
      p_makeup_cost
    ]) as value(amount)
    where value.amount is null
       or value.amount not between 0 and 1000000
  ) then
    raise exception 'INVALID_CHECKIN_RULE';
  end if;

  begin
    insert into public.checkin_rule_versions as rule (
      effective_from,
      monday_reward,
      tuesday_reward,
      wednesday_reward,
      thursday_reward,
      friday_reward,
      saturday_reward,
      sunday_reward,
      makeup_cost,
      created_by
    ) values (
      p_effective_from,
      p_monday_reward,
      p_tuesday_reward,
      p_wednesday_reward,
      p_thursday_reward,
      p_friday_reward,
      p_saturday_reward,
      p_sunday_reward,
      p_makeup_cost,
      v_admin_id
    )
    returning rule.* into v_rule;
  exception
    when unique_violation then
      raise exception 'CHECKIN_RULE_DATE_EXISTS';
  end;

  return v_rule;
end;
$$;

alter table public.activities enable row level security;
alter table public.activity_claims enable row level security;
alter table public.site_notifications enable row level security;
alter table public.notification_reads enable row level security;
alter table public.notification_claims enable row level security;
alter table public.checkin_rule_versions enable row level security;
alter table public.player_checkins enable row level security;

revoke all on table public.activities from public, anon, authenticated;
revoke all on table public.activity_claims from public, anon, authenticated;
revoke all on table public.site_notifications from public, anon, authenticated;
revoke all on table public.notification_reads from public, anon, authenticated;
revoke all on table public.notification_claims from public, anon, authenticated;
revoke all on table public.checkin_rule_versions from public, anon, authenticated;
revoke all on table public.player_checkins from public, anon, authenticated;

grant select on table public.site_notifications to anon, authenticated;
grant select on table public.notification_reads to authenticated;

drop policy if exists "visitors can read active site notifications" on public.site_notifications;
create policy "visitors can read active site notifications"
on public.site_notifications for select
to anon, authenticated
using (
  is_active = true
  and visible_at <= now()
  and (expires_at is null or expires_at > now())
);

drop policy if exists "players can read own notification reads" on public.notification_reads;
create policy "players can read own notification reads"
on public.notification_reads for select
to authenticated
using (auth.uid() = user_id);

do $$
begin
  alter publication supabase_realtime add table public.site_notifications;
exception when duplicate_object then
  null;
end;
$$;

do $$
begin
  alter publication supabase_realtime add table public.notification_reads;
exception when duplicate_object then
  null;
end;
$$;

revoke execute on function public.site_local_date() from public, anon, authenticated;
revoke execute on function public.require_registered_user() from public, anon, authenticated;
revoke execute on function public.require_site_admin() from public, anon, authenticated;
revoke execute on function public.checkin_rule_for_date(date) from public, anon, authenticated;
revoke execute on function public.validate_public_url(text, boolean) from public, anon, authenticated;

revoke execute on function public.list_active_activities() from public, anon, authenticated;
revoke execute on function public.claim_activity_reward(uuid, uuid) from public, anon, authenticated;
revoke execute on function public.admin_list_activities() from public, anon, authenticated;
revoke execute on function public.admin_save_activity(uuid, text, text, text, text, text, timestamptz, timestamptz, timestamptz, bigint) from public, anon, authenticated;
revoke execute on function public.admin_unpublish_activity(uuid) from public, anon, authenticated;
revoke execute on function public.list_site_notifications(timestamptz, uuid, integer) from public, anon, authenticated;
revoke execute on function public.count_unread_site_notifications() from public, anon, authenticated;
revoke execute on function public.mark_site_notification_read(uuid) from public, anon, authenticated;
revoke execute on function public.claim_site_notification_reward(uuid, uuid) from public, anon, authenticated;
revoke execute on function public.admin_list_site_notifications() from public, anon, authenticated;
revoke execute on function public.admin_publish_site_notification(text, text, bigint, timestamptz, timestamptz) from public, anon, authenticated;
revoke execute on function public.admin_disable_site_notification(uuid) from public, anon, authenticated;
revoke execute on function public.get_checkin_month(date) from public, anon, authenticated;
revoke execute on function public.perform_daily_checkin(uuid) from public, anon, authenticated;
revoke execute on function public.perform_makeup_checkin(date, text, uuid) from public, anon, authenticated;
revoke execute on function public.admin_list_checkin_rules() from public, anon, authenticated;
revoke execute on function public.admin_create_checkin_rule(date, bigint, bigint, bigint, bigint, bigint, bigint, bigint, bigint) from public, anon, authenticated;

grant execute on function public.list_active_activities() to anon, authenticated;
grant execute on function public.list_site_notifications(timestamptz, uuid, integer) to anon, authenticated;

grant execute on function public.claim_activity_reward(uuid, uuid) to authenticated;
grant execute on function public.admin_list_activities() to authenticated;
grant execute on function public.admin_save_activity(uuid, text, text, text, text, text, timestamptz, timestamptz, timestamptz, bigint) to authenticated;
grant execute on function public.admin_unpublish_activity(uuid) to authenticated;
grant execute on function public.count_unread_site_notifications() to authenticated;
grant execute on function public.mark_site_notification_read(uuid) to authenticated;
grant execute on function public.claim_site_notification_reward(uuid, uuid) to authenticated;
grant execute on function public.admin_list_site_notifications() to authenticated;
grant execute on function public.admin_publish_site_notification(text, text, bigint, timestamptz, timestamptz) to authenticated;
grant execute on function public.admin_disable_site_notification(uuid) to authenticated;
grant execute on function public.get_checkin_month(date) to authenticated;
grant execute on function public.perform_daily_checkin(uuid) to authenticated;
grant execute on function public.perform_makeup_checkin(date, text, uuid) to authenticated;
grant execute on function public.admin_list_checkin_rules() to authenticated;
grant execute on function public.admin_create_checkin_rule(date, bigint, bigint, bigint, bigint, bigint, bigint, bigint, bigint) to authenticated;

create or replace function public.prevent_engagement_record_mutation()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
  if tg_op = 'DELETE'
     and not exists (
       select 1
       from public.profiles as profile
       where profile.id = old.user_id
     ) then
    return old;
  end if;

  raise exception 'ENGAGEMENT_RECORD_IMMUTABLE';
end;
$$;

revoke execute on function public.prevent_engagement_record_mutation()
from public, anon, authenticated;

drop trigger if exists engagement_record_immutable on public.activity_claims;
create trigger engagement_record_immutable
before update or delete on public.activity_claims
for each row
execute function public.prevent_engagement_record_mutation();

drop trigger if exists engagement_record_immutable on public.notification_claims;
create trigger engagement_record_immutable
before update or delete on public.notification_claims
for each row
execute function public.prevent_engagement_record_mutation();

drop trigger if exists engagement_record_immutable on public.player_checkins;
create trigger engagement_record_immutable
before update or delete on public.player_checkins
for each row
execute function public.prevent_engagement_record_mutation();
