create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text not null unique,
  game_name text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (username ~ '^[a-z0-9_]+$'),
  check (char_length(username) between 3 and 20),
  check (char_length(game_name) between 1 and 16),
  check (game_name = btrim(game_name)),
  check (game_name !~ '[[:cntrl:]]')
);

alter table public.profiles
  drop constraint if exists profiles_username_check;
alter table public.profiles
  add constraint profiles_username_check
  check (username ~ '^[a-z0-9_]+$' and char_length(username) between 3 and 20);

alter table public.profiles enable row level security;

drop policy if exists "players can read own profile" on public.profiles;
drop policy if exists "players can create own profile" on public.profiles;
drop policy if exists "players can update own profile" on public.profiles;

create policy "players can read own profile"
on public.profiles for select
to authenticated
using (auth.uid() = id);

create policy "players can create own profile"
on public.profiles for insert
to authenticated
with check (
  auth.uid() = id
  and username = split_part(coalesce(auth.jwt() ->> 'email', ''), '@', 1)
);

create policy "players can update own profile"
on public.profiles for update
to authenticated
using (auth.uid() = id)
with check (
  auth.uid() = id
  and username = split_part(coalesce(auth.jwt() ->> 'email', ''), '@', 1)
);

revoke all on table public.profiles from public, anon;
grant select, insert, update on table public.profiles to authenticated;

alter table public.online_games add column if not exists x_player_name text;
alter table public.online_games add column if not exists o_player_name text;

update public.online_games
set x_player_name = '匿名玩家·' || upper(substr(replace(x_player::text, '-', ''), 1, 4))
where x_player_name is null;

update public.online_games
set o_player_name = '匿名玩家·' || upper(substr(replace(o_player::text, '-', ''), 1, 4))
where o_player is not null and o_player_name is null;

alter table public.online_games alter column x_player_name set not null;

alter table public.online_games
  drop constraint if exists online_games_room_code_check;
alter table public.online_games
  add constraint online_games_room_code_check
  check (room_code ~ '^[A-HJ-NP-Z2-9]+$' and char_length(room_code) = 6);

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.online_games'::regclass
      and conname = 'online_games_x_player_name_check'
  ) then
    alter table public.online_games
      add constraint online_games_x_player_name_check
      check (char_length(x_player_name) between 1 and 16);
  end if;
  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.online_games'::regclass
      and conname = 'online_games_o_player_name_check'
  ) then
    alter table public.online_games
      add constraint online_games_o_player_name_check
      check (o_player_name is null or char_length(o_player_name) between 1 and 16);
  end if;
end;
$$;

create or replace function public.resolve_online_player_name(p_guest_name text)
returns text
language plpgsql
stable
security definer
set search_path = public, pg_temp
as $$
declare
  v_name text;
begin
  select game_name into v_name
  from public.profiles
  where id = auth.uid();

  if found then return v_name; end if;

  v_name := btrim(coalesce(p_guest_name, ''));
  if v_name !~ '^匿名玩家·[A-HJ-NP-Z2-9][A-HJ-NP-Z2-9][A-HJ-NP-Z2-9][A-HJ-NP-Z2-9]$' then
    raise exception 'INVALID_PLAYER_NAME';
  end if;
  return v_name;
end;
$$;

revoke all on function public.resolve_online_player_name(text) from public, anon, authenticated;

create table if not exists public.player_wallets (
  user_id uuid primary key references auth.users(id) on delete cascade,
  balance bigint not null default 100 check (balance >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.coin_ledger (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  delta bigint not null check (delta <> 0),
  balance_after bigint not null check (balance_after >= 0),
  event_type text not null,
  reference_id text,
  idempotency_key text not null unique,
  created_at timestamptz not null default now()
);

create index if not exists coin_ledger_user_created_idx
on public.coin_ledger (user_id, created_at desc);

create table if not exists public.admins (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

create table if not exists public.redeem_codes (
  id uuid primary key default gen_random_uuid(),
  code_digest text not null unique,
  code_hint text not null,
  amount bigint not null check (amount between 1 and 1000000),
  max_claims integer not null check (max_claims between 1 and 100000),
  claim_count integer not null default 0 check (claim_count between 0 and max_claims),
  expires_at timestamptz,
  is_active boolean not null default true,
  created_by uuid not null references auth.users(id),
  created_at timestamptz not null default now()
);

create table if not exists public.redeem_claims (
  code_id uuid not null references public.redeem_codes(id) on delete restrict,
  user_id uuid not null references auth.users(id) on delete cascade,
  amount bigint not null check (amount > 0),
  claimed_at timestamptz not null default now(),
  primary key (code_id, user_id)
);

alter table public.player_wallets enable row level security;
alter table public.coin_ledger enable row level security;
alter table public.admins enable row level security;
alter table public.redeem_codes enable row level security;
alter table public.redeem_claims enable row level security;

revoke all on table public.player_wallets from public, anon, authenticated;
revoke all on table public.coin_ledger from public, anon, authenticated;
revoke all on table public.admins from public, anon, authenticated;
revoke all on table public.redeem_codes from public, anon, authenticated;
revoke all on table public.redeem_claims from public, anon, authenticated;

alter table public.online_games add column if not exists wager_amount integer not null default 0;
alter table public.online_games add column if not exists x_stake_locked boolean not null default false;
alter table public.online_games add column if not exists o_stake_locked boolean not null default false;
alter table public.online_games add column if not exists wager_settled_at timestamptz;
alter table public.online_games add column if not exists finish_reason text;
alter table public.online_games add column if not exists x_last_seen_at timestamptz;
alter table public.online_games add column if not exists o_last_seen_at timestamptz;

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.online_games'::regclass
      and conname = 'online_games_wager_amount_check'
  ) then
    alter table public.online_games
      add constraint online_games_wager_amount_check
      check (wager_amount in (0, 10, 50, 100));
  end if;
end;
$$;

create or replace function public.prevent_coin_ledger_mutation()
returns trigger
language plpgsql
set search_path = public, pg_temp
as $$
begin
  raise exception 'COIN_LEDGER_IMMUTABLE';
end;
$$;

drop trigger if exists coin_ledger_immutable on public.coin_ledger;
create trigger coin_ledger_immutable
before update or delete on public.coin_ledger
for each row execute function public.prevent_coin_ledger_mutation();

create or replace function public.is_economy_admin(p_user uuid default auth.uid())
returns boolean
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select exists (select 1 from public.admins where user_id = p_user);
$$;

create or replace function public.apply_coin_delta(
  p_user uuid,
  p_delta bigint,
  p_event_type text,
  p_reference_id text,
  p_idempotency_key text
)
returns bigint
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_balance bigint;
  v_existing bigint;
begin
  if p_user is null or p_delta = 0 then raise exception 'INVALID_COIN_DELTA'; end if;

  select balance into v_balance
  from public.player_wallets
  where user_id = p_user
  for update;
  if not found then raise exception 'REGISTERED_ACCOUNT_REQUIRED'; end if;

  select balance_after into v_existing
  from public.coin_ledger
  where idempotency_key = p_idempotency_key;
  if found then return v_existing; end if;

  if v_balance + p_delta < 0 then raise exception 'INSUFFICIENT_COINS'; end if;
  v_balance := v_balance + p_delta;

  update public.player_wallets
  set balance = v_balance, updated_at = now()
  where user_id = p_user;

  insert into public.coin_ledger (
    user_id, delta, balance_after, event_type, reference_id, idempotency_key
  ) values (
    p_user, p_delta, v_balance, p_event_type, p_reference_id, p_idempotency_key
  );
  return v_balance;
end;
$$;

create or replace function public.ensure_profile_wallet()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
  insert into public.player_wallets (user_id, balance)
  values (new.id, 100)
  on conflict (user_id) do nothing;

  if found then
    insert into public.coin_ledger (
      user_id, delta, balance_after, event_type, reference_id, idempotency_key
    ) values (
      new.id, 100, 100, 'initial_grant', new.id::text, 'initial_grant:' || new.id::text
    ) on conflict (idempotency_key) do nothing;
  end if;
  return new;
end;
$$;

drop trigger if exists profiles_create_wallet on public.profiles;
create trigger profiles_create_wallet
after insert on public.profiles
for each row execute function public.ensure_profile_wallet();

insert into public.player_wallets (user_id, balance)
select id, 100 from public.profiles
on conflict (user_id) do nothing;

insert into public.coin_ledger (
  user_id, delta, balance_after, event_type, reference_id, idempotency_key
)
select id, 100, 100, 'initial_grant', id::text, 'initial_grant:' || id::text
from public.profiles
on conflict (idempotency_key) do nothing;

create or replace function public.generate_redeem_code()
returns text
language plpgsql
volatile
set search_path = public, pg_temp
as $$
declare
  v_alphabet constant text := 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789';
  v_code text := '';
  v_index integer;
begin
  for v_index in 0..11 loop
    v_code := v_code || substr(
      v_alphabet,
      (get_byte(gen_random_bytes(1), 0) % length(v_alphabet)) + 1,
      1
    );
  end loop;
  return v_code;
end;
$$;

create or replace function public.lock_online_stake(
  p_user uuid,
  p_game_id uuid,
  p_round integer,
  p_amount integer
)
returns void
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
  if p_amount = 0 then return; end if;
  if p_amount not in (10, 50, 100) then raise exception 'INVALID_WAGER'; end if;
  if not exists (select 1 from public.profiles where id = p_user) then
    raise exception 'REGISTERED_ACCOUNT_REQUIRED';
  end if;
  perform public.apply_coin_delta(
    p_user,
    -p_amount,
    'wager_lock',
    p_game_id::text,
    'wager_lock:' || p_game_id::text || ':' || p_round::text || ':' || p_user::text
  );
end;
$$;

create or replace function public.settle_online_wager(
  p_game_id uuid,
  p_result text,
  p_winner uuid default null,
  p_finish_reason text default null
)
returns void
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_game public.online_games;
  v_pot bigint;
begin
  select * into v_game from public.online_games where id = p_game_id for update;
  if not found or v_game.wager_amount = 0 or v_game.wager_settled_at is not null then return; end if;

  if p_result in ('x_win', 'o_win') then
    if p_winner is null then raise exception 'WAGER_WINNER_REQUIRED'; end if;
    v_pot := v_game.wager_amount
      * ((case when v_game.x_stake_locked then 1 else 0 end)
      + (case when v_game.o_stake_locked then 1 else 0 end));
    if v_pot > 0 then
      perform public.apply_coin_delta(
        p_winner,
        v_pot,
        'wager_payout',
        p_game_id::text,
        'wager_payout:' || p_game_id::text || ':' || v_game.round::text || ':' || p_winner::text
      );
    end if;
  elsif p_result in ('draw', 'cancelled', 'expired') then
    if v_game.x_stake_locked then
      perform public.apply_coin_delta(
        v_game.x_player,
        v_game.wager_amount,
        'wager_refund',
        p_game_id::text,
        'wager_refund:' || p_game_id::text || ':' || v_game.round::text || ':' || v_game.x_player::text
      );
    end if;
    if v_game.o_stake_locked and v_game.o_player is not null then
      perform public.apply_coin_delta(
        v_game.o_player,
        v_game.wager_amount,
        'wager_refund',
        p_game_id::text,
        'wager_refund:' || p_game_id::text || ':' || v_game.round::text || ':' || v_game.o_player::text
      );
    end if;
  else
    raise exception 'INVALID_WAGER_RESULT';
  end if;

  update public.online_games
  set x_stake_locked = false,
      o_stake_locked = false,
      wager_settled_at = now(),
      finish_reason = coalesce(p_finish_reason, finish_reason)
  where id = p_game_id;
end;
$$;

create or replace function public.settle_online_game_trigger()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_winner uuid;
begin
  if old.status = 'playing' and new.status in ('x_win', 'o_win', 'draw') then
    v_winner := case
      when new.status = 'x_win' then new.x_player
      when new.status = 'o_win' then new.o_player
      else null
    end;
    perform public.settle_online_wager(
      new.id,
      new.status,
      v_winner,
      coalesce(new.finish_reason, case when new.status = 'draw' then 'draw' else 'normal' end)
    );
  end if;
  return new;
end;
$$;

drop trigger if exists online_game_settle_wager on public.online_games;
create trigger online_game_settle_wager
after update of status on public.online_games
for each row execute function public.settle_online_game_trigger();

create or replace function public.refund_expired_online_wagers(p_user uuid)
returns void
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_game public.online_games;
begin
  for v_game in
    select * from public.online_games
    where expires_at < now()
      and wager_amount > 0
      and wager_settled_at is null
      and (x_player = p_user or o_player = p_user)
    for update
  loop
    perform public.settle_online_wager(v_game.id, 'expired', null, 'expired');
    if v_game.status = 'waiting' then
      delete from public.online_games where id = v_game.id;
    else
      update public.online_games
      set status = 'abandoned', finish_reason = 'expired', version = version + 1
      where id = v_game.id;
    end if;
  end loop;
end;
$$;

create or replace function public.get_economy_snapshot()
returns table (balance bigint, is_admin boolean)
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_user uuid := auth.uid();
begin
  if v_user is null or not exists (select 1 from public.profiles where id = v_user) then
    raise exception 'REGISTERED_ACCOUNT_REQUIRED';
  end if;
  perform public.refund_expired_online_wagers(v_user);
  return query
  select wallet.balance, public.is_economy_admin(v_user)
  from public.player_wallets wallet
  where wallet.user_id = v_user;
end;
$$;

create or replace function public.redeem_coin_code(p_code text)
returns table (granted_amount bigint, balance bigint)
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_user uuid := auth.uid();
  v_normalized text := upper(regexp_replace(trim(coalesce(p_code, '')), '[[:space:]-]', '', 'g'));
  v_code public.redeem_codes;
begin
  if v_user is null or not exists (select 1 from public.profiles where id = v_user) then
    raise exception 'REGISTERED_ACCOUNT_REQUIRED';
  end if;
  if char_length(v_normalized) <> 12 or v_normalized !~ '^[A-HJ-NP-Z2-9]+$' then
    raise exception 'CODE_NOT_FOUND';
  end if;

  select * into v_code
  from public.redeem_codes
  where code_digest = encode(digest(v_normalized, 'sha256'), 'hex')
  for update;
  if not found then raise exception 'CODE_NOT_FOUND'; end if;
  if not v_code.is_active then raise exception 'CODE_DISABLED'; end if;
  if v_code.expires_at is not null and v_code.expires_at <= now() then raise exception 'CODE_EXPIRED'; end if;
  if v_code.claim_count >= v_code.max_claims then raise exception 'CODE_EXHAUSTED'; end if;
  if exists (
    select 1 from public.redeem_claims where code_id = v_code.id and user_id = v_user
  ) then raise exception 'CODE_ALREADY_REDEEMED'; end if;

  insert into public.redeem_claims (code_id, user_id, amount)
  values (v_code.id, v_user, v_code.amount);
  update public.redeem_codes set claim_count = claim_count + 1 where id = v_code.id;
  granted_amount := v_code.amount;
  balance := public.apply_coin_delta(
    v_user,
    v_code.amount,
    'redeem_code',
    v_code.id::text,
    'redeem:' || v_code.id::text || ':' || v_user::text
  );
  return next;
end;
$$;

create or replace function public.create_redeem_code(
  p_amount integer,
  p_max_claims integer,
  p_expires_at timestamptz default null
)
returns table (id uuid, code text, amount bigint, max_claims integer, expires_at timestamptz)
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_user uuid := auth.uid();
  v_raw text;
  v_id uuid;
  v_attempt integer;
begin
  if not public.is_economy_admin(v_user) then raise exception 'ADMIN_REQUIRED'; end if;
  if p_amount not between 1 and 1000000 then raise exception 'INVALID_CODE_AMOUNT'; end if;
  if p_max_claims not between 1 and 100000 then raise exception 'INVALID_CODE_LIMIT'; end if;
  if p_expires_at is not null and p_expires_at <= now() then raise exception 'INVALID_CODE_EXPIRY'; end if;

  for v_attempt in 1..20 loop
    begin
      v_raw := public.generate_redeem_code();
      insert into public.redeem_codes (
        code_digest, code_hint, amount, max_claims, expires_at, created_by
      ) values (
        encode(digest(v_raw, 'sha256'), 'hex'),
        substr(v_raw, 1, 4) || '-****-' || substr(v_raw, 9, 4),
        p_amount,
        p_max_claims,
        p_expires_at,
        v_user
      ) returning redeem_codes.id into v_id;
      id := v_id;
      code := substr(v_raw, 1, 4) || '-' || substr(v_raw, 5, 4) || '-' || substr(v_raw, 9, 4);
      amount := p_amount;
      max_claims := p_max_claims;
      expires_at := p_expires_at;
      return next;
      return;
    exception when unique_violation then
      null;
    end;
  end loop;
  raise exception 'CODE_GENERATION_FAILED';
end;
$$;

create or replace function public.list_redeem_codes()
returns table (
  id uuid,
  code_hint text,
  amount bigint,
  max_claims integer,
  claim_count integer,
  expires_at timestamptz,
  is_active boolean,
  created_at timestamptz
)
language plpgsql
stable
security definer
set search_path = public, pg_temp
as $$
begin
  if not public.is_economy_admin(auth.uid()) then raise exception 'ADMIN_REQUIRED'; end if;
  return query
  select code.id, code.code_hint, code.amount, code.max_claims, code.claim_count,
    code.expires_at, code.is_active, code.created_at
  from public.redeem_codes code
  order by code.created_at desc
  limit 100;
end;
$$;

create or replace function public.disable_redeem_code(p_code_id uuid)
returns void
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
  if not public.is_economy_admin(auth.uid()) then raise exception 'ADMIN_REQUIRED'; end if;
  update public.redeem_codes set is_active = false where id = p_code_id;
end;
$$;

drop function if exists public.create_online_game(text);
drop function if exists public.create_online_game(text, text);
drop function if exists public.join_online_game(text, text);
create or replace function public.create_online_game(
  p_game_type text,
  p_guest_name text,
  p_wager_amount integer default 0
)
returns setof public.online_games
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_user uuid := auth.uid();
  v_player_name text := public.resolve_online_player_name(p_guest_name);
  v_game public.online_games;
  v_attempt integer;
begin
  if v_user is null then raise exception 'AUTH_REQUIRED'; end if;
  if p_game_type not in ('tic_tac_toe', 'gomoku') then raise exception 'INVALID_GAME_TYPE'; end if;
  if p_wager_amount not in (0, 10, 50, 100) then raise exception 'INVALID_WAGER'; end if;
  if p_wager_amount > 0 and not exists (select 1 from public.profiles where id = v_user) then
    raise exception 'REGISTERED_ACCOUNT_REQUIRED';
  end if;
  perform public.refund_expired_online_wagers(v_user);

  select * into v_game
  from public.online_games
  where x_player = v_user and o_player is null and status = 'waiting' and game_type = p_game_type
  order by created_at desc limit 1 for update;
  if found and v_game.expires_at >= now() and v_game.wager_amount = p_wager_amount then
    update public.online_games
    set x_player_name = v_player_name, x_last_seen_at = now(), updated_at = now(),
      expires_at = now() + interval '24 hours'
    where id = v_game.id returning * into v_game;
    return next v_game;
    return;
  elsif found then
    perform public.settle_online_wager(v_game.id, 'cancelled', null, 'cancelled');
    delete from public.online_games where id = v_game.id;
  end if;

  for v_attempt in 1..20 loop
    begin
      insert into public.online_games (
        room_code, game_type, x_player, x_player_name, board, wager_amount, x_last_seen_at
      ) values (
        public.generate_online_room_code(), p_game_type, v_user, v_player_name,
        public.online_empty_board(p_game_type), p_wager_amount, now()
      ) returning * into v_game;
      perform public.lock_online_stake(v_user, v_game.id, v_game.round, p_wager_amount);
      if p_wager_amount > 0 then
        update public.online_games set x_stake_locked = true where id = v_game.id returning * into v_game;
      end if;
      return next v_game;
      return;
    exception when unique_violation then
      null;
    end;
  end loop;
  raise exception 'ROOM_CODE_UNAVAILABLE';
end;
$$;

create or replace function public.preview_online_game(p_room_code text, p_game_type text)
returns table (game_type text, host_name text, wager_amount integer, status text)
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_code text := upper(trim(p_room_code));
  v_game public.online_games;
begin
  if auth.uid() is null then raise exception 'AUTH_REQUIRED'; end if;
  if char_length(v_code) <> 6 or v_code !~ '^[A-HJ-NP-Z2-9]+$' then
    raise exception 'ROOM_NOT_FOUND';
  end if;
  select * into v_game from public.online_games where room_code = v_code for update;
  if not found then raise exception 'ROOM_NOT_FOUND'; end if;
  if v_game.game_type <> p_game_type then raise exception 'ROOM_GAME_MISMATCH'; end if;
  if v_game.expires_at < now() then
    perform public.settle_online_wager(v_game.id, 'expired', null, 'expired');
    delete from public.online_games where id = v_game.id;
    raise exception 'ROOM_EXPIRED';
  end if;
  if v_game.status <> 'waiting' or v_game.o_player is not null then raise exception 'ROOM_FULL'; end if;
  game_type := v_game.game_type;
  host_name := v_game.x_player_name;
  wager_amount := v_game.wager_amount;
  status := v_game.status;
  return next;
end;
$$;

create or replace function public.join_online_game(p_room_code text, p_game_type text, p_guest_name text)
returns setof public.online_games
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_user uuid := auth.uid();
  v_player_name text := public.resolve_online_player_name(p_guest_name);
  v_code text := upper(trim(p_room_code));
  v_game public.online_games;
begin
  if v_user is null then raise exception 'AUTH_REQUIRED'; end if;
  if char_length(v_code) <> 6 or v_code !~ '^[A-HJ-NP-Z2-9]+$' then
    raise exception 'ROOM_NOT_FOUND';
  end if;
  if p_game_type not in ('tic_tac_toe', 'gomoku') then raise exception 'INVALID_GAME_TYPE'; end if;

  select * into v_game from public.online_games where room_code = v_code for update;
  if not found then raise exception 'ROOM_NOT_FOUND'; end if;
  if v_game.game_type <> p_game_type then raise exception 'ROOM_GAME_MISMATCH'; end if;
  if v_game.expires_at < now() then
    perform public.settle_online_wager(v_game.id, 'expired', null, 'expired');
    delete from public.online_games where id = v_game.id;
    raise exception 'ROOM_EXPIRED';
  end if;

  if v_game.x_player = v_user or v_game.o_player = v_user then
    update public.online_games
    set x_last_seen_at = case when x_player = v_user then now() else x_last_seen_at end,
        o_last_seen_at = case when o_player = v_user then now() else o_last_seen_at end,
        expires_at = now() + interval '24 hours', updated_at = now()
    where id = v_game.id returning * into v_game;
    return next v_game;
    return;
  end if;
  if v_game.o_player is not null or v_game.status <> 'waiting' then raise exception 'ROOM_FULL'; end if;
  if v_game.wager_amount > 0 and not exists (select 1 from public.profiles where id = v_user) then
    raise exception 'REGISTERED_ACCOUNT_REQUIRED';
  end if;

  perform public.lock_online_stake(v_user, v_game.id, v_game.round, v_game.wager_amount);
  update public.online_games
  set o_player = v_user,
      o_player_name = v_player_name,
      o_stake_locked = wager_amount > 0,
      o_last_seen_at = now(),
      status = 'playing',
      updated_at = now(),
      expires_at = now() + interval '24 hours',
      version = version + 1
  where id = v_game.id returning * into v_game;
  return next v_game;
end;
$$;

create or replace function public.heartbeat_online_game(p_game_id uuid)
returns setof public.online_games
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_user uuid := auth.uid();
  v_game public.online_games;
begin
  update public.online_games
  set x_last_seen_at = case when x_player = v_user then now() else x_last_seen_at end,
      o_last_seen_at = case when o_player = v_user then now() else o_last_seen_at end,
      updated_at = now()
  where id = p_game_id and (x_player = v_user or o_player = v_user)
  returning * into v_game;
  if not found then raise exception 'NOT_A_PLAYER'; end if;
  return next v_game;
end;
$$;

create or replace function public.claim_online_disconnect(p_game_id uuid)
returns setof public.online_games
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_user uuid := auth.uid();
  v_game public.online_games;
  v_winner_mark text;
  v_opponent_seen timestamptz;
begin
  select * into v_game from public.online_games where id = p_game_id for update;
  if not found then raise exception 'ROOM_NOT_FOUND'; end if;
  if v_game.status <> 'playing' then raise exception 'GAME_NOT_PLAYING'; end if;
  if v_game.x_player = v_user then
    v_winner_mark := 'X';
    v_opponent_seen := coalesce(v_game.o_last_seen_at, v_game.created_at);
  elsif v_game.o_player = v_user then
    v_winner_mark := 'O';
    v_opponent_seen := coalesce(v_game.x_last_seen_at, v_game.created_at);
  else
    raise exception 'NOT_A_PLAYER';
  end if;
  if v_opponent_seen > now() - interval '30 seconds' then raise exception 'OPPONENT_STILL_ONLINE'; end if;

  update public.online_games
  set status = lower(v_winner_mark) || '_win',
      current_mark = v_winner_mark,
      x_score = x_score + case when v_winner_mark = 'X' then 1 else 0 end,
      o_score = o_score + case when v_winner_mark = 'O' then 1 else 0 end,
      finish_reason = 'disconnect',
      updated_at = now(),
      expires_at = now() + interval '1 hour',
      version = version + 1
  where id = v_game.id returning * into v_game;
  return next v_game;
end;
$$;

create or replace function public.request_online_rematch(p_game_id uuid)
returns setof public.online_games
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_user uuid := auth.uid();
  v_game public.online_games;
  v_x_ready boolean;
  v_o_ready boolean;
begin
  if v_user is null then raise exception 'AUTH_REQUIRED'; end if;
  select * into v_game from public.online_games where id = p_game_id for update;
  if not found then raise exception 'ROOM_NOT_FOUND'; end if;
  if v_game.status not in ('x_win', 'o_win', 'draw') then raise exception 'GAME_NOT_FINISHED'; end if;

  v_x_ready := v_game.x_rematch;
  v_o_ready := v_game.o_rematch;
  if v_game.x_player = v_user then v_x_ready := true;
  elsif v_game.o_player = v_user then v_o_ready := true;
  else raise exception 'NOT_A_PLAYER';
  end if;

  if v_x_ready and v_o_ready then
    perform public.lock_online_stake(v_game.x_player, v_game.id, v_game.round + 1, v_game.wager_amount);
    perform public.lock_online_stake(v_game.o_player, v_game.id, v_game.round + 1, v_game.wager_amount);
    update public.online_games
    set board = public.online_empty_board(game_type),
        x_order = '{}'::smallint[], o_order = '{}'::smallint[], move_history = '{}'::smallint[],
        current_mark = 'X', status = 'playing', winning_line = '{}'::smallint[],
        round = round + 1, x_rematch = false, o_rematch = false,
        x_undos_remaining = 3, o_undos_remaining = 3,
        undo_request_mark = null, undo_requested_at = null, undo_expires_at = null,
        x_stake_locked = wager_amount > 0, o_stake_locked = wager_amount > 0,
        wager_settled_at = null, finish_reason = null,
        x_last_seen_at = now(), o_last_seen_at = now(),
        updated_at = now(), expires_at = now() + interval '24 hours', version = version + 1
    where id = v_game.id returning * into v_game;
  else
    update public.online_games
    set x_rematch = v_x_ready, o_rematch = v_o_ready,
        updated_at = now(), expires_at = now() + interval '24 hours', version = version + 1
    where id = v_game.id returning * into v_game;
  end if;
  return next v_game;
end;
$$;

create or replace function public.leave_online_game(p_game_id uuid)
returns void
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_user uuid := auth.uid();
  v_game public.online_games;
  v_winner_mark text;
begin
  if v_user is null then raise exception 'AUTH_REQUIRED'; end if;
  select * into v_game from public.online_games where id = p_game_id for update;
  if not found then return; end if;
  if v_game.x_player <> v_user and v_game.o_player is distinct from v_user then raise exception 'NOT_A_PLAYER'; end if;
  if v_game.o_player is null then
    perform public.settle_online_wager(v_game.id, 'cancelled', null, 'cancelled');
    delete from public.online_games where id = v_game.id;
    return;
  end if;
  if v_game.status = 'playing' and v_game.wager_amount > 0 then
    v_winner_mark := case when v_game.x_player = v_user then 'O' else 'X' end;
    update public.online_games
    set status = lower(v_winner_mark) || '_win',
        current_mark = v_winner_mark,
        x_score = x_score + case when v_winner_mark = 'X' then 1 else 0 end,
        o_score = o_score + case when v_winner_mark = 'O' then 1 else 0 end,
        finish_reason = 'active_exit',
        undo_request_mark = null, undo_requested_at = null, undo_expires_at = null,
        updated_at = now(), expires_at = now() + interval '1 hour', version = version + 1
    where id = v_game.id;
    return;
  end if;
  if v_game.status = 'playing' then
    update public.online_games
    set status = 'abandoned', undo_request_mark = null, undo_requested_at = null,
        undo_expires_at = null, updated_at = now(), expires_at = now() + interval '1 hour',
        version = version + 1
    where id = v_game.id;
  end if;
end;
$$;

revoke all on function public.is_economy_admin(uuid) from public;
revoke all on function public.apply_coin_delta(uuid, bigint, text, text, text) from public;
revoke all on function public.lock_online_stake(uuid, uuid, integer, integer) from public;
revoke all on function public.settle_online_wager(uuid, text, uuid, text) from public;
revoke all on function public.refund_expired_online_wagers(uuid) from public;

+revoke execute on function public.get_economy_snapshot() from public, anon;
revoke execute on function public.redeem_coin_code(text) from public, anon;
revoke execute on function public.create_redeem_code(integer, integer, timestamptz) from public, anon;
revoke execute on function public.list_redeem_codes() from public, anon;
revoke execute on function public.disable_redeem_code(uuid) from public, anon;
revoke execute on function public.create_online_game(text, text, integer) from public, anon;
revoke execute on function public.preview_online_game(text, text) from public, anon;
revoke execute on function public.join_online_game(text, text, text) from public, anon;
revoke execute on function public.heartbeat_online_game(uuid) from public, anon;
revoke execute on function public.claim_online_disconnect(uuid) from public, anon;
revoke execute on function public.request_online_rematch(uuid) from public, anon;
revoke execute on function public.leave_online_game(uuid) from public, anon;

grant execute on function public.get_economy_snapshot() to authenticated;
grant execute on function public.redeem_coin_code(text) to authenticated;
grant execute on function public.create_redeem_code(integer, integer, timestamptz) to authenticated;
grant execute on function public.list_redeem_codes() to authenticated;
grant execute on function public.disable_redeem_code(uuid) to authenticated;
grant execute on function public.create_online_game(text, text, integer) to authenticated;
grant execute on function public.preview_online_game(text, text) to authenticated;
grant execute on function public.join_online_game(text, text, text) to authenticated;
grant execute on function public.heartbeat_online_game(uuid) to authenticated;
grant execute on function public.claim_online_disconnect(uuid) to authenticated;
grant execute on function public.request_online_rematch(uuid) to authenticated;
grant execute on function public.leave_online_game(uuid) to authenticated;
