create table if not exists public.shop_products (
  sku text primary key check (sku in ('makeup_card', 'rename_card')),
  name varchar(40) not null,
  description text not null,
  price bigint not null default 0 check (price >= 0),
  is_active boolean not null default false,
  per_user_limit integer check (per_user_limit is null or per_user_limit > 0),
  sort_order integer not null,
  updated_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.shop_purchases (
  id uuid primary key default gen_random_uuid(),
  request_id uuid not null unique,
  user_id uuid not null references auth.users(id),
  sku text not null references public.shop_products(sku),
  unit_price bigint not null check (unit_price >= 0),
  quantity integer not null default 1 check (quantity = 1),
  total_price bigint not null check (total_price >= 0),
  created_at timestamptz not null default now(),
  check (total_price = unit_price * quantity)
);

create table if not exists public.player_items (
  user_id uuid not null references auth.users(id) on delete cascade,
  sku text not null references public.shop_products(sku),
  quantity bigint not null default 0 check (quantity >= 0),
  updated_at timestamptz not null default now(),
  primary key (user_id, sku)
);

create table if not exists public.item_ledger (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id),
  sku text not null references public.shop_products(sku),
  delta bigint not null check (delta <> 0),
  quantity_after bigint not null check (quantity_after >= 0),
  event_type text not null,
  reference_id text,
  idempotency_key text not null unique,
  created_at timestamptz not null default now()
);

create index if not exists shop_purchases_user_sku_idx
on public.shop_purchases (user_id, sku, created_at);

create index if not exists item_ledger_user_created_idx
on public.item_ledger (user_id, created_at desc);

insert into public.shop_products (
  sku, name, description, price, is_active, per_user_limit, sort_order
) values
  ('makeup_card', '补签卡', '抵扣一次补签金币费用', 0, false, null, 10),
  ('rename_card', '改名卡', '修改一次注册账号游戏名', 0, false, null, 20)
on conflict (sku) do update
set name = excluded.name,
    description = excluded.description,
    sort_order = excluded.sort_order;

create or replace function public.prevent_item_ledger_mutation()
returns trigger
language plpgsql
set search_path = public, pg_temp
as $$
begin
  raise exception 'ITEM_LEDGER_IMMUTABLE';
end;
$$;

drop trigger if exists item_ledger_immutable on public.item_ledger;
create trigger item_ledger_immutable
before update or delete on public.item_ledger
for each row execute function public.prevent_item_ledger_mutation();

create or replace function public.apply_item_delta(
  p_user uuid,
  p_sku text,
  p_delta bigint,
  p_event_type text,
  p_reference_id text,
  p_idempotency_key text
)
returns bigint
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_quantity bigint;
  v_existing public.item_ledger%rowtype;
begin
  if p_user is null or p_delta = 0 then
    raise exception 'INVALID_ITEM_DELTA';
  end if;
  if p_sku not in ('makeup_card', 'rename_card')
     or not exists (select 1 from public.shop_products where sku = p_sku) then
    raise exception 'ITEM_NOT_FOUND';
  end if;
  if nullif(btrim(coalesce(p_event_type, '')), '') is null
     or nullif(btrim(coalesce(p_idempotency_key, '')), '') is null then
    raise exception 'INVALID_ITEM_DELTA';
  end if;

  select ledger.*
  into v_existing
  from public.item_ledger as ledger
  where ledger.idempotency_key = p_idempotency_key;

  if found then
    if v_existing.user_id <> p_user or v_existing.sku <> p_sku then
      raise exception 'INVALID_ITEM_IDEMPOTENCY';
    end if;
    return v_existing.quantity_after;
  end if;

  insert into public.player_items (user_id, sku, quantity)
  values (p_user, p_sku, 0)
  on conflict (user_id, sku) do nothing;

  select item.quantity
  into v_quantity
  from public.player_items as item
  where item.user_id = p_user and item.sku = p_sku
  for update;

  select ledger.*
  into v_existing
  from public.item_ledger as ledger
  where ledger.idempotency_key = p_idempotency_key;

  if found then
    if v_existing.user_id <> p_user or v_existing.sku <> p_sku then
      raise exception 'INVALID_ITEM_IDEMPOTENCY';
    end if;
    return v_existing.quantity_after;
  end if;

  if v_quantity + p_delta < 0 then
    raise exception 'INSUFFICIENT_ITEMS';
  end if;

  v_quantity := v_quantity + p_delta;
  update public.player_items as item
  set quantity = v_quantity,
      updated_at = now()
  where item.user_id = p_user and item.sku = p_sku;

  insert into public.item_ledger (
    user_id, sku, delta, quantity_after, event_type, reference_id, idempotency_key
  ) values (
    p_user, p_sku, p_delta, v_quantity, p_event_type, p_reference_id, p_idempotency_key
  );

  return v_quantity;
end;
$$;

create or replace function public.list_shop_products()
returns table (
  sku text,
  name text,
  description text,
  price bigint,
  is_active boolean,
  per_user_limit integer,
  purchased_count bigint,
  remaining_limit bigint,
  updated_at timestamptz
)
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select
    product.sku,
    product.name::text,
    product.description,
    product.price,
    product.is_active,
    product.per_user_limit,
    case
      when exists (select 1 from public.profiles where id = auth.uid())
      then count(purchase.id)
      else 0
    end as purchased_count,
    case
      when product.per_user_limit is null then null
      else greatest(
        product.per_user_limit::bigint - case
          when exists (select 1 from public.profiles where id = auth.uid())
          then count(purchase.id)
          else 0
        end,
        0
      )
    end as remaining_limit,
    product.updated_at
  from public.shop_products as product
  left join public.shop_purchases as purchase
    on purchase.sku = product.sku
   and purchase.user_id = auth.uid()
  where product.is_active and product.price >= 1
  group by product.sku
  order by product.sort_order, product.sku;
$$;

create or replace function public.get_player_inventory()
returns table (sku text, quantity bigint)
language plpgsql
stable
security definer
set search_path = public, pg_temp
as $$
declare
  v_user_id uuid := public.require_registered_user();
begin
  return query
  select product.sku, coalesce(item.quantity, 0)::bigint
  from public.shop_products as product
  left join public.player_items as item
    on item.user_id = v_user_id and item.sku = product.sku
  where product.sku in ('makeup_card', 'rename_card')
  order by product.sort_order, product.sku;
end;
$$;

create or replace function public.admin_list_shop_products()
returns table (
  sku text,
  name text,
  description text,
  price bigint,
  is_active boolean,
  per_user_limit integer,
  sort_order integer,
  updated_at timestamptz
)
language plpgsql
stable
security definer
set search_path = public, pg_temp
as $$
begin
  perform public.require_site_admin();
  return query
  select
    product.sku,
    product.name::text,
    product.description,
    product.price,
    product.is_active,
    product.per_user_limit,
    product.sort_order,
    product.updated_at
  from public.shop_products as product
  order by product.sort_order, product.sku;
end;
$$;

create or replace function public.admin_update_shop_product(
  p_sku text,
  p_price bigint,
  p_is_active boolean,
  p_per_user_limit integer
)
returns table (
  sku text,
  name text,
  description text,
  price bigint,
  is_active boolean,
  per_user_limit integer,
  sort_order integer,
  updated_at timestamptz
)
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_admin_id uuid := public.require_site_admin();
begin
  if p_sku not in ('makeup_card', 'rename_card') then
    raise exception 'PRODUCT_NOT_FOUND';
  end if;
  if p_price is null or p_price not between 0 and 1000000
     or p_is_active is null
     or (p_is_active and p_price < 1)
     or (p_per_user_limit is not null and p_per_user_limit not between 1 and 100000) then
    raise exception 'INVALID_PRODUCT_CONFIG';
  end if;

  return query
  update public.shop_products as product
  set price = p_price,
      is_active = p_is_active,
      per_user_limit = p_per_user_limit,
      updated_by = v_admin_id,
      updated_at = now()
  where product.sku = p_sku
  returning
    product.sku,
    product.name::text,
    product.description,
    product.price,
    product.is_active,
    product.per_user_limit,
    product.sort_order,
    product.updated_at;
end;
$$;

create or replace function public.buy_shop_product(p_sku text, p_request_id uuid)
returns table (
  sku text,
  price_paid bigint,
  balance bigint,
  quantity bigint,
  remaining_limit bigint
)
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_user_id uuid := public.require_registered_user();
  v_product public.shop_products%rowtype;
  v_purchase public.shop_purchases%rowtype;
  v_purchase_id uuid := gen_random_uuid();
  v_purchased_count bigint;
  v_balance bigint;
  v_quantity bigint;
begin
  if p_request_id is null then
    raise exception 'INVALID_REQUEST_ID';
  end if;

  select product.*
  into v_product
  from public.shop_products as product
  where product.sku = p_sku
  for update;

  if not found then raise exception 'PRODUCT_NOT_FOUND'; end if;

  select purchase.*
  into v_purchase
  from public.shop_purchases as purchase
  where purchase.request_id = p_request_id;

  if found then
    if v_purchase.user_id <> v_user_id or v_purchase.sku <> p_sku then
      raise exception 'INVALID_REQUEST_ID';
    end if;
    select wallet.balance into v_balance
    from public.player_wallets as wallet where wallet.user_id = v_user_id;
    select coalesce(item.quantity, 0) into v_quantity
    from public.player_items as item
    where item.user_id = v_user_id and item.sku = p_sku;
    select count(*) into v_purchased_count
    from public.shop_purchases as purchase
    where purchase.user_id = v_user_id and purchase.sku = p_sku;
    return query select
      v_purchase.sku,
      v_purchase.unit_price,
      v_balance,
      coalesce(v_quantity, 0),
      case when v_product.per_user_limit is null then null
        else greatest(v_product.per_user_limit::bigint - v_purchased_count, 0) end;
    return;
  end if;

  if not v_product.is_active then raise exception 'PRODUCT_INACTIVE'; end if;
  if v_product.price < 1 then raise exception 'PRODUCT_PRICE_INVALID'; end if;

  select count(*) into v_purchased_count
  from public.shop_purchases as purchase
  where purchase.user_id = v_user_id and purchase.sku = p_sku;

  if v_product.per_user_limit is not null
     and v_purchased_count >= v_product.per_user_limit then
    raise exception 'PURCHASE_LIMIT_REACHED';
  end if;

  v_balance := public.apply_coin_delta(
    v_user_id,
    -v_product.price,
    'shop_purchase',
    v_purchase_id::text,
    'shop_purchase:' || p_request_id::text
  );

  insert into public.shop_purchases (
    id, request_id, user_id, sku, unit_price, quantity, total_price
  ) values (
    v_purchase_id, p_request_id, v_user_id, p_sku, v_product.price, 1, v_product.price
  ) returning * into v_purchase;

  v_quantity := public.apply_item_delta(
    v_user_id,
    p_sku,
    1,
    'shop_purchase',
    v_purchase_id::text,
    'shop_item:' || p_request_id::text
  );

  v_purchased_count := v_purchased_count + 1;
  return query select
    v_purchase.sku,
    v_purchase.unit_price,
    v_balance,
    v_quantity,
    case when v_product.per_user_limit is null then null
      else greatest(v_product.per_user_limit::bigint - v_purchased_count, 0) end;
end;
$$;

create or replace function public.rename_with_item(p_game_name text, p_request_id uuid)
returns table (username text, game_name text, rename_card_quantity bigint)
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_user_id uuid := public.require_registered_user();
  v_game_name text := btrim(coalesce(p_game_name, ''));
  v_profile public.profiles%rowtype;
  v_quantity bigint;
begin
  if p_request_id is null then raise exception 'INVALID_REQUEST_ID'; end if;
  if char_length(v_game_name) not between 1 and 16
     or v_game_name ~ '[[:cntrl:]]' then
    raise exception 'INVALID_GAME_NAME';
  end if;

  select profile.*
  into v_profile
  from public.profiles as profile
  where profile.id = v_user_id
  for update;

  if v_profile.game_name = v_game_name then
    select coalesce(item.quantity, 0)
    into v_quantity
    from public.player_items as item
    where item.user_id = v_user_id and item.sku = 'rename_card';
    return query select v_profile.username, v_profile.game_name, coalesce(v_quantity, 0);
    return;
  end if;

  v_quantity := public.apply_item_delta(
    v_user_id,
    'rename_card',
    -1,
    'rename',
    v_user_id::text,
    'rename:' || p_request_id::text
  );

  update public.profiles as profile
  set game_name = v_game_name,
      updated_at = now()
  where profile.id = v_user_id
  returning profile.* into v_profile;

  return query select v_profile.username, v_profile.game_name, v_quantity;
end;
$$;

create or replace function public.perform_makeup_checkin(
  p_date date,
  p_payment_method text,
  p_request_id uuid
)
returns table (
  checkin_date date,
  reward_amount bigint,
  balance bigint,
  checkin_type text,
  payment_method text,
  payment_amount bigint
)
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_user_id uuid := public.require_registered_user();
  v_today date := public.site_local_date();
  v_current_month date := date_trunc('month', v_today)::date;
  v_rule public.checkin_rule_versions%rowtype;
  v_checkin public.player_checkins%rowtype;
  v_reward bigint;
  v_balance bigint;
  v_payment_amount bigint;
begin
  if p_request_id is null then raise exception 'INVALID_REQUEST_ID'; end if;

  select wallet.balance into v_balance
  from public.player_wallets as wallet
  where wallet.user_id = v_user_id
  for update;

  if p_date is null or p_date >= v_today then raise exception 'MAKEUP_DATE_INVALID'; end if;
  if date_trunc('month', p_date)::date <> v_current_month then
    raise exception 'MAKEUP_OUTSIDE_CURRENT_MONTH';
  end if;
  if p_payment_method not in ('coins', 'item') then
    raise exception 'INVALID_MAKEUP_PAYMENT';
  end if;
  if exists (
    select 1 from public.player_checkins as checkin
    where checkin.user_id = v_user_id and checkin.checkin_date = p_date
  ) then
    raise exception 'CHECKIN_ALREADY_DONE';
  end if;

  select rule.* into v_rule
  from public.checkin_rule_for_date(p_date) as rule;
  if not found then raise exception 'INVALID_CHECKIN_RULE'; end if;

  v_reward := case extract(isodow from p_date)::integer
    when 1 then v_rule.monday_reward when 2 then v_rule.tuesday_reward
    when 3 then v_rule.wednesday_reward when 4 then v_rule.thursday_reward
    when 5 then v_rule.friday_reward when 6 then v_rule.saturday_reward
    when 7 then v_rule.sunday_reward
  end;
  v_payment_amount := case when p_payment_method = 'item' then 1 else v_rule.makeup_cost end;

  begin
    insert into public.player_checkins as checkin (
      user_id, checkin_date, checkin_type, reward_amount, payment_method, payment_amount
    ) values (
      v_user_id, p_date, 'makeup', v_reward, p_payment_method, v_payment_amount
    ) returning checkin.* into v_checkin;
  exception when unique_violation then
    raise exception 'CHECKIN_ALREADY_DONE';
  end;

  if p_payment_method = 'coins' and v_rule.makeup_cost <> 0 then
    v_balance := public.apply_coin_delta(
      v_user_id, -v_rule.makeup_cost, 'checkin_makeup_cost', p_date::text,
      'checkin:makeup:cost:' || v_user_id::text || ':' || p_date::text
    );
  elsif p_payment_method = 'item' then
    perform public.apply_item_delta(
      v_user_id, 'makeup_card', -1, 'checkin_makeup', p_date::text,
      'makeup_item:' || v_user_id::text || ':' || p_date::text
    );
  end if;

  if v_reward <> 0 then
    v_balance := public.apply_coin_delta(
      v_user_id, v_reward, 'checkin_makeup_reward', p_date::text,
      'checkin:makeup:reward:' || v_user_id::text || ':' || p_date::text
    );
  end if;

  return query select
    v_checkin.checkin_date, v_checkin.reward_amount, v_balance,
    v_checkin.checkin_type, v_checkin.payment_method, v_checkin.payment_amount;
end;
$$;

alter table public.shop_products enable row level security;
alter table public.shop_purchases enable row level security;
alter table public.player_items enable row level security;
alter table public.item_ledger enable row level security;

revoke all on table public.shop_products from public;
revoke all on table public.shop_products from anon, authenticated;
revoke all on table public.shop_purchases from public;
revoke all on table public.shop_purchases from anon, authenticated;
revoke all on table public.player_items from public;
revoke all on table public.player_items from anon, authenticated;
revoke all on table public.item_ledger from public;
revoke all on table public.item_ledger from anon, authenticated;

revoke all on function public.prevent_item_ledger_mutation() from public, anon, authenticated;
revoke all on function public.apply_item_delta(uuid, text, bigint, text, text, text) from public, anon, authenticated;

revoke execute on function public.list_shop_products() from public, anon, authenticated;
revoke execute on function public.get_player_inventory() from public, anon, authenticated;
revoke execute on function public.buy_shop_product(text, uuid) from public, anon, authenticated;
revoke execute on function public.admin_list_shop_products() from public, anon, authenticated;
revoke execute on function public.admin_update_shop_product(text, bigint, boolean, integer) from public, anon, authenticated;
revoke execute on function public.rename_with_item(text, uuid) from public, anon, authenticated;
revoke execute on function public.perform_makeup_checkin(date, text, uuid) from public, anon, authenticated;

grant execute on function public.list_shop_products() to anon, authenticated;
grant execute on function public.get_player_inventory() to authenticated;
grant execute on function public.buy_shop_product(text, uuid) to authenticated;
grant execute on function public.admin_list_shop_products() to authenticated;
grant execute on function public.admin_update_shop_product(text, bigint, boolean, integer) to authenticated;
grant execute on function public.rename_with_item(text, uuid) to authenticated;
grant execute on function public.perform_makeup_checkin(date, text, uuid) to authenticated;
